### PR TITLE
feat(*): Upgrade JDF format to 2.0

### PR DESCRIPTION
**Pull request by GeekyShacklebolt**
* Replace sample images
* Replace sample pdf
* Refactor main-style.tex with JDF format 2.0
* Refactor main.tex with new JDF content

### CODE REVIEW

**Comment by CuriousLearner** [comment]
I have fixed the enumeration of the reference list in the previous commit. Please fix the font-size thing, and then we should be good to go.

**Comment by GeekyShacklebolt** [comment]
Hey!
I have fixed the font size issue with tables and caption along with some minor fixes like giving underline to links and removing cookiecutter tag of `project_description`. Please have a look at the PR and let me know if further changes are required.

**Comment by CuriousLearner** [comment]
Hey @GeekyShacklebolt 

Please see the below images. It seems like the heading 4 is still off (I think it need italics) and there are still other discrepancies. Can you read the original doc and as per recommendations, modify the LaTeX, please?

Left side is the original JDF-2.0 doc and right side is the sample PDF in this PR, currently.

Screenshot 2019-05-30 at 1 46 04 AM
Screenshot 2019-05-30 at 1 44 48 AM
Screenshot 2019-05-30 at 1 44 33 AM

Please let me know if you've any questions/thoughts/suggestions.

**Comment by GeekyShacklebolt** [comment]
Hey @CuriousLearner 

The image of document JDF2.0 you shared is different than the one I have. Seems like it has been changed since you first shared it to me, because the one I have, doesn't have Italics as default body text. Can you please share the original document again?

Also, please let me know if I should remove the blue color of `clickable email`, `reference links` and change the color of `hyperlinks` to match with JDF 2.0?

**Pull request merged**
